version: '3'
services:
  dev:
    image: "node:14.5.0-stretch-slim"
    volumes:
        - ./estimator:/usr/src/service
    working_dir: /usr/src/service
    command: "npm start"
    ports:
      - 8080:8080