version: '3'
services:
  estimator:
    build: .
    #healthcheck:
    #  test: curl --fail -s http://127.0.0.1:8000/ || exit 1
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    restart: "unless-stopped"
    volumes:
      - ./jira_backlog_estimator:/app/jira_backlog_estimator
    ports:
        - "8000:8000"
